# Site settings
title: 'Code Sandbox'
description: 
  en: "Mathias Berwig's personal site"
  pt: "Site pessoal de Mathias Berwig"
url: 'https://mathiasberwig.github.io'
google_analytics: UA-85925131-1
# disqus_shortname: 'your-disqus-name'
languages: ['en', 'pt']
default_lang: 'en'

# Author info
author:
  name: 'Mathias Berwig'
  birthday: 1996-02-10
  email: mathiasberwig@gmail.com
#  twitter_username: mathiasberwig
  facebook_username: MathiasBerwig
  github_username:  mathiasberwig
  linkedin_username:  mathiasberwig

# Folder scopes
defaults:
  - scope:
      path: _posts
      type: posts
    values:
        layout: post
  - scope:
      path: _works
    values:
      layout: page
      type: work

# Build settings
gems: ['jekyll-paginate', 'jekyll-polyglot']
include: ['_pages', '_works']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'deploy.sh']
exclude_from_localization: ['js/particles.js', 'images', 'css', 'fonts']
destination: _site
permalink: /:title/
paginate: 10
paginate_path: '/blog/page:num/'
highlighter: rouge
parallel_localization: false

# Polyglot Translation
t:
  general:
    and:
      en: and
      pt: e
  header_panel:
    profile_photo_alt: 
      en: My Profile Photo
      pt: Minha foto de perfil
    blog: 
      en: Blog
      pt: Blog
    about:
      en: About
      pt: Sobre
    on_github:
      en: on GitHub
      pt: no GitHub
    on_linkedin:
      en: on LinkedIn
      pt: no LinkedIn
    on_facebook:
      en: on Facebook
      pt: no Facebook
    on_twitter:
      en: on Twitter
      pt: no Twitter
    subscribe:
      en: Subscribe
      pt: Assinar
  footer:
    based_on:
      en: Based on
      pt: Baseado em
    built_with:
      en: Built with  
      pt: Construído com 
    and_hatchet:
      en: and an hatchet
      pt: e um machado
  pagination:
    page:
      en: Page
      pt: Página
    of:
      en: of
      pt: de
    previous_page: 
      en: ← Newer Posts
      pt: ← Posts mais recentes
    next_page:
      en: Older Posts →
      pt: Posts mais antigos →
  post_meta:
    tag_on:
      en: 'on'
      pt: em
    read_more:
      en: Read more
      pt: Ler mais
  portfolio:
    btn_more:
      en: MORE
      pt: MAIS