# Site settings
title: 'Code Sandbox'
description: "Mathias Berwig's personal blog"
url: 'http://mathiasberwig.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Mathias Berwig'
  email: mathiasberwig@gmail.com
#  twitter_username: mathiasberwig
  facebook_username: MathiasBerwig
  github_username:  mathiasberwig
  linkedin_username:  mathiasberwig

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
